# Generated by Django 3.1.4 on 2020-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
