# Generated by Django 3.1.4 on 2020-12-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20201205_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
