# Generated by Django 3.1.4 on 2021-02-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20210122_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
    ]
