# Generated by Django 3.1.4 on 2021-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_auto_20210203_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='description',
            field=models.CharField(default='', max_length=35000),
        ),
    ]
