# Generated by Django 3.1.4 on 2021-02-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0005_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='category',
        ),
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.ManyToManyField(to='codex.Category'),
        ),
    ]
